// <auto-generated />
using System;
using Inventario.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inventario.Infrastructure.Migrations
{
    [DbContext(typeof(InventarioDbContext))]
    [Migration("20260817091421_QuitarCamposNoListadosActivo")]
    partial class QuitarCamposNoListadosActivo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Inventario.Domain.Entities.Activo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("EficienciaPct")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Fabricante")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("FechaInstalacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FinGarantia")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NumeroSerie")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("PotenciaNominalKw")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime?>("ProximaRevision")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SistemaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimaRevision")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("SistemaId");

                    b.ToTable("activos", (string)null);
                });

            modelBuilder.Entity("Inventario.Domain.Entities.ClienteDatos", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ContractRef")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("contract_ref");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_date");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("longtext");

                    b.Property<string>("ProjectType")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("project_type");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.ToTable("cliente_datos", (string)null);
                });

            modelBuilder.Entity("Inventario.Domain.Entities.Componente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivoId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("SensorId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ActivoId");

                    b.HasIndex("SensorId")
                        .IsUnique();

                    b.ToTable("componentes", (string)null);
                });

            modelBuilder.Entity("Inventario.Domain.Entities.Documento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActivoId")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("EntidadId")
                        .HasColumnType("int");

                    b.Property<string>("EntidadTipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RutaAlmacenamiento")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UsuarioSubio")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ActivoId");

                    b.HasIndex("EntidadTipo", "EntidadId");

                    b.ToTable("documentos", (string)null);
                });

            modelBuilder.Entity("Inventario.Domain.Entities.Mantenimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivoId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Costo")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("FechaEjecucion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaProgramada")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("longtext");

                    b.Property<string>("Responsable")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ActivoId");

                    b.ToTable("mantenimientos", (string)null);
                });

            modelBuilder.Entity("Inventario.Domain.Entities.Movimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("longtext");

                    b.Property<string>("Destino")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("longtext");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Origen")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Usuario")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ActivoId");

                    b.ToTable("movimientos", (string)null);
                });

            modelBuilder.Entity("Inventario.Domain.Entities.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("longtext");

                    b.Property<int>("EntidadId")
                        .HasColumnType("int");

                    b.Property<string>("EntidadTipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("longtext");

                    b.Property<int>("TipoPermiso")
                        .HasColumnType("int");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Usuario", "EntidadTipo", "EntidadId")
                        .IsUnique();

                    b.ToTable("permisos", (string)null);
                });

            modelBuilder.Entity("Inventario.Domain.Entities.Sistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("LocalizacionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("sistemas", (string)null);
                });

            modelBuilder.Entity("Inventario.Domain.Entities.UsuarioInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("longtext");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("usuarios_inventario", (string)null);
                });

            modelBuilder.Entity("Inventario.Domain.Entities.Activo", b =>
                {
                    b.HasOne("Inventario.Domain.Entities.Sistema", "Sistema")
                        .WithMany("Activos")
                        .HasForeignKey("SistemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sistema");
                });

            modelBuilder.Entity("Inventario.Domain.Entities.Componente", b =>
                {
                    b.HasOne("Inventario.Domain.Entities.Activo", "Activo")
                        .WithMany("Componentes")
                        .HasForeignKey("ActivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Inventario.Domain.ValueObjects.RangoMedicion", "RangoMedicion", b1 =>
                        {
                            b1.Property<int>("ComponenteId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Maximo")
                                .HasColumnType("decimal(65,30)")
                                .HasColumnName("rango_maximo");

                            b1.Property<decimal>("Minimo")
                                .HasColumnType("decimal(65,30)")
                                .HasColumnName("rango_minimo");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("rango_unidad");

                            b1.HasKey("ComponenteId");

                            b1.ToTable("componentes");

                            b1.WithOwner()
                                .HasForeignKey("ComponenteId");
                        });

                    b.Navigation("Activo");

                    b.Navigation("RangoMedicion");
                });

            modelBuilder.Entity("Inventario.Domain.Entities.Documento", b =>
                {
                    b.HasOne("Inventario.Domain.Entities.Activo", null)
                        .WithMany("Documentos")
                        .HasForeignKey("ActivoId");
                });

            modelBuilder.Entity("Inventario.Domain.Entities.Mantenimiento", b =>
                {
                    b.HasOne("Inventario.Domain.Entities.Activo", "Activo")
                        .WithMany("Mantenimientos")
                        .HasForeignKey("ActivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activo");
                });

            modelBuilder.Entity("Inventario.Domain.Entities.Movimiento", b =>
                {
                    b.HasOne("Inventario.Domain.Entities.Activo", "Activo")
                        .WithMany("Movimientos")
                        .HasForeignKey("ActivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activo");
                });

            modelBuilder.Entity("Inventario.Domain.Entities.Activo", b =>
                {
                    b.Navigation("Componentes");

                    b.Navigation("Documentos");

                    b.Navigation("Mantenimientos");

                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("Inventario.Domain.Entities.Sistema", b =>
                {
                    b.Navigation("Activos");
                });
#pragma warning restore 612, 618
        }
    }
}
